name: Brandon Kester
description: My thoughts and projects
title: Brandon Kester's thoughts and projects
url: https://www.brandonkester.com/
highlighter: rouge
timezone: America/Los_Angeles
safe: true
lsi: false
